<Project Sdk="Microsoft.NET.Sdk.Razor">
        <PropertyGroup>
                <TargetFrameworks>net9.0-android</TargetFrameworks>
                <AcceptAndroidSDKLicenses>true</AcceptAndroidSDKLicenses>
                <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
                <TargetFrameworks>net9.0-android</TargetFrameworks>
                <OutputType>Exe</OutputType>
                <RootNamespace>QuantumSecure</RootNamespace>
                <UseMaui>true</UseMaui>
                <SingleProject>true</SingleProject>
                <SelfContained>true</SelfContained>
                <ImplicitUsings>enable</ImplicitUsings>
                <!-- Display name -->
                <ApplicationTitle>Quantum Secure</ApplicationTitle>
                <!-- App Identifier -->
                <ApplicationId>click.freenetworkmonitor.quantumsecure</ApplicationId>
                <ApplicationIdGuid>d4f21b0e-2c97-4c50-b003-dca43bd9a888</ApplicationIdGuid>
                <!-- Versions -->
                <ApplicationDisplayVersion>0.5.21</ApplicationDisplayVersion>
                <ApplicationVersion>521</ApplicationVersion>
                <SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>
                <AndroidSdkDirectory>/usr/lib/android-sdk</AndroidSdkDirectory>
                <Nullable>enable</Nullable>
                <NoWarn>CS8618</NoWarn>
                <AndroidSupportedAbis>arm64-v8a;armeabi-v7a</AndroidSupportedAbis>
                <AndroidBundleConfigurationFile>BundleConfig.json</AndroidBundleConfigurationFile>

        </PropertyGroup>
        <PropertyGroup Condition="'$(Configuration)'=='Release-Dev'">
                <DefineConstants>DEV</DefineConstants>
        </PropertyGroup>
        <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU' or '$(Configuration)'=='Release-Dev'">
                <AndroidPackageFormat>aab</AndroidPackageFormat>
                <AndroidSigningKeyAlias>networkmonitormaui</AndroidSigningKeyAlias>
                <AndroidSigningKeyStore>/home/mahadeva/code/securefiles/networkmonitormaui.keystore</AndroidSigningKeyStore>
                <AndroidSigningKeyPass>$(ANDROID_SIGNING_KEY_PASS)</AndroidSigningKeyPass>
                <AndroidSigningStorePass>$(ANDROID_SIGNING_KEY_PASS)</AndroidSigningStorePass>
                <AndroidKeyStore>true</AndroidKeyStore>
                <Optimize>true</Optimize>
                <PublishTrimmed>false</PublishTrimmed>
                <RunAOTCompilation>false</RunAOTCompilation>
                <EnableDefaultStaticWebAssets>true</EnableDefaultStaticWebAssets>
        </PropertyGroup>

        <ItemGroup>
                <!-- App Icon -->
                <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#FFFFFF" />
                <!-- Splash Screen -->
                <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#FFFFFF" BaseSize="128,128" />
                <!-- Images -->
                <MauiImage Include="Resources\Images\*" />
                <!--<MauiImage Update="Resources\Images\logo.svg" BaseSize="168,208" /> -->
                <!-- Custom Fonts -->
                <MauiFont Include="Resources\Fonts\*" />
                <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
                <MauiAsset Include="Resources\Raw\**" Exclude="Resources\Raw\openssl-windows\**;Resources\Raw\windowsdlls\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
                <MauiStyles Include="Resources\Styles\*" />
        </ItemGroup>


   <ItemGroup>
    <AndroidNativeLibrary Include="Platforms/Android/jniLibs/arm64-v8a/libprocwrapper.so">
      <Abi>arm64-v8a</Abi>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms/Android/jniLibs/arm64-v8a/libopenssl_exec.so">
      <Abi>arm64-v8a</Abi>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms/Android/jniLibs/arm64-v8a/libnmap_exec.so">
      <Abi>arm64-v8a</Abi>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms/Android/jniLibs/arm64-v8a/libssl.so">
      <Abi>arm64-v8a</Abi>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms/Android/jniLibs/arm64-v8a/libcrypto.so">
      <Abi>arm64-v8a</Abi>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms/Android/jniLibs/arm64-v8a/libc++_shared.so">
      <Abi>arm64-v8a</Abi>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms/Android/jniLibs/arm64-v8a/oqsprovider.so">
      <Abi>arm64-v8a</Abi>
    </AndroidNativeLibrary>
    <AndroidNativeLibrary Include="Platforms/Android/jniLibs/arm64-v8a/openssl.so">
      <Abi>arm64-v8a</Abi>
    </AndroidNativeLibrary>
  </ItemGroup>

  <ItemGroup>
  <AndroidNativeLibrary Include="Platforms/Android/jniLibs/armeabi-v7a/libc++_shared.so">
    <Abi>armeabi-v7a</Abi>
  </AndroidNativeLibrary>
  <AndroidNativeLibrary Include="Platforms/Android/jniLibs/armeabi-v7a/libcrypto.so">
    <Abi>armeabi-v7a</Abi>
  </AndroidNativeLibrary>
  <AndroidNativeLibrary Include="Platforms/Android/jniLibs/armeabi-v7a/libcrypto.so.3">
    <Abi>armeabi-v7a</Abi>
  </AndroidNativeLibrary>
  <AndroidNativeLibrary Include="Platforms/Android/jniLibs/armeabi-v7a/libssl.so">
    <Abi>armeabi-v7a</Abi>
  </AndroidNativeLibrary>
  <AndroidNativeLibrary Include="Platforms/Android/jniLibs/armeabi-v7a/libssl.so.3">
    <Abi>armeabi-v7a</Abi>
  </AndroidNativeLibrary>
  <AndroidNativeLibrary Include="Platforms/Android/jniLibs/armeabi-v7a/nmap">
    <Abi>armeabi-v7a</Abi>
  </AndroidNativeLibrary>
  <AndroidNativeLibrary Include="Platforms/Android/jniLibs/armeabi-v7a/openssl">
    <Abi>armeabi-v7a</Abi>
  </AndroidNativeLibrary>
  <AndroidNativeLibrary Include="Platforms/Android/jniLibs/armeabi-v7a/openssl.so">
    <Abi>armeabi-v7a</Abi>
  </AndroidNativeLibrary>
  <AndroidNativeLibrary Include="Platforms/Android/jniLibs/armeabi-v7a/oqsprovider.so">
    <Abi>armeabi-v7a</Abi>
  </AndroidNativeLibrary>
  <AndroidNativeLibrary Include="Platforms/Android/jniLibs/armeabi-v7a/ssl_helper">
    <Abi>armeabi-v7a</Abi>
  </AndroidNativeLibrary>
</ItemGroup>


        <ItemGroup>
                <PackageReference Include="MetroLog.Maui" Version="2.1.0" />
                <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="9.0.100" />
                <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.8" />
                <PackageReference Include="CommunityToolkit.Maui" Version="11.2.0" />
                <PackageReference Include="Microsoft.Toolkit.Mvvm" Version="7.1.2" />
                <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.100" />
                <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.100" />
                <PackageReference Include="Microsoft.Maui.Core" Version="9.0.100" />
                <PackageReference Include="Microsoft.Maui.Essentials" Version="9.0.100" />
                <PackageReference Include="Microsoft.Maui.Graphics" Version="9.0.100" />
                <PackageReference Include="Syncfusion.Maui.Toolkit" Version="1.0.6" />
                <PackageReference Include="MatBlazor" Version="2.10.0" />
                <PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.8" />
                <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.8" />
                <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.8" />
                <PackageReference Include="Microsoft.JSInterop" Version="9.0.8" />
        </ItemGroup>
        <ItemGroup>
                <ProjectReference Include="..\NetworkMonitorChatRazorLib\NetworkMonitorChatRazorLib-Android.csproj" />
	</ItemGroup>
	 <ItemGroup>
                <ProjectReference Include="..\NetworkMonitorMaui\NetworkMonitorMaui-Android.csproj" />
        </ItemGroup>
        <ItemGroup>
                <AndroidAsset Include="$(OutputPath)/*.dll">
                        <Link>assemblies\%(FileName)%(Extension)</Link>
                </AndroidAsset>
        </ItemGroup>
        <PropertyGroup>
                <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        </PropertyGroup>

</Project>

