<Project Sdk="Microsoft.NET.Sdk.Razor">


    <PropertyGroup>

        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>

        <OutputType>Exe</OutputType>
       

        <!-- Display name -->
        <ApplicationTitle>Quantum Secure</ApplicationTitle>

        <!-- App Identifier -->
        <ApplicationId>click.freenetworkmonitor.quantumsecure</ApplicationId>

        <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
        <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <SelfContained>true</SelfContained>
        <IncludeSymbols>true</IncludeSymbols>
        <!-- https://github.com/CommunityToolkit/Maui/issues/2205 -->
        <NoWarn>XC0103</NoWarn>
        <WindowsPackageType>MSIX</WindowsPackageType>
          <LinkerBehavior>None</LinkerBehavior>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <DefaultItemExcludes>$(DefaultItemExcludes);Tests\**</DefaultItemExcludes>

    </PropertyGroup>

    <ItemGroup>
        <!-- App Icon -->

        <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#FFFFFF" />

        <MauiIcon Include="Resources\Splash\splash.svg">
            <Color>#FFFFFF</Color>
            <ForegroundFile>Resources\AppIcon\appiconfg.svg</ForegroundFile>
        </MauiIcon>

        <!-- Splash Screen -->

        <!-- Images -->
        <MauiImage Include="Resources\Images\*" />
        <MauiImage Update="Resources\Images\dotneplaceholder.png" Resize="True" BaseSize="300,185" />

        <!-- Custom Fonts -->
        <MauiFont Include="Resources/Fonts/OpenSans-Regular.ttf" Alias="OpenSansRegular" />
        <MauiFont Include="Resources/Fonts/OpenSans-Semibold.ttf" Alias="OpenSansSemibold" />

        <MauiAsset Include="Resources\Raw\appsettings.json" />
        <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
        <MauiAsset Include="Resources\Raw\openssl-windows\**" Exclude="Resources\Raw\openssl-android\**;Resources\Raw\dlls\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />

    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.251106002" />
        <PackageReference Include="MetroLog.Maui" Version="2.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.1" />
        <PackageReference Include="CommunityToolkit.Maui" Version="13.0.0" />
        <PackageReference Include="Microsoft.Toolkit.Mvvm" Version="7.1.2" />
        <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.11" />
        <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.11" />
        <PackageReference Include="Microsoft.Maui.Core" Version="10.0.11" />
        <PackageReference Include="Microsoft.Maui.Essentials" Version="10.0.11" />
        <PackageReference Include="Microsoft.Maui.Graphics" Version="10.0.11" />
        <PackageReference Include="Syncfusion.Maui.Toolkit" Version="1.0.8" />
        <PackageReference Include="MatBlazor" Version="2.10.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components" Version="10.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.1" />
        <PackageReference Include="Microsoft.JSInterop" Version="10.0.1" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3590-prerelease" />

    </ItemGroup>

   
    <ItemGroup>
      <None Remove="Resources\Images\Logos\logosquare.scale-100.png" />
      <None Remove="Resources\Images\Logos\logosquare.scale-125.png" />
      <None Remove="Resources\Images\Logos\logosquare.scale-150.png" />
      <None Remove="Resources\Images\Logos\logosquare.scale-200.png" />
      <None Remove="Resources\Images\Logos\logosquare.scale-400.png" />
      <None Remove="Resources\Images\Logos\placeholder.scale-100.png" />
      <None Remove="Resources\Images\Logos\placeholder.scale-125.png" />
      <None Remove="Resources\Images\Logos\placeholder.scale-150.png" />
      <None Remove="Resources\Images\Logos\placeholder.scale-200.png" />
      <None Remove="Resources\Images\Logos\placeholder.scale-400.png" />
      <None Remove="Resources\Images\SquareLogo\logomediumsquare.scale-100.png" />
      <None Remove="Resources\Images\SquareLogo\logomediumsquare.scale-125.png" />
      <None Remove="Resources\Images\SquareLogo\logomediumsquare.scale-150.png" />
      <None Remove="Resources\Images\SquareLogo\logomediumsquare.scale-200.png" />
      <None Remove="Resources\Images\SquareLogo\logomediumsquare.scale-400.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.scale-100.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.scale-125.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.scale-150.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.scale-200.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.scale-400.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-16.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-16_altform-lightunplated.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-16_altform-unplated.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-24.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-24_altform-lightunplated.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-24_altform-unplated.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-256.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-256_altform-lightunplated.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-256_altform-unplated.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-32.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-32_altform-lightunplated.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-32_altform-unplated.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-48.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-48_altform-lightunplated.png" />
      <None Remove="Resources\Images\SquareLogo\logosquare.targetsize-48_altform-unplated.png" />
      <None Remove="Resources\Images\SquareLogo\placeholder.scale-100.png" />
      <None Remove="Resources\Images\SquareLogo\placeholder.scale-125.png" />
      <None Remove="Resources\Images\SquareLogo\placeholder.scale-150.png" />
      <None Remove="Resources\Images\SquareLogo\placeholder.scale-200.png" />
      <None Remove="Resources\Images\SquareLogo\placeholder.scale-400.png" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="Resources\Images\Logos\logosquare.scale-100.png" />
      <Content Include="Resources\Images\Logos\logosquare.scale-125.png" />
      <Content Include="Resources\Images\Logos\logosquare.scale-150.png" />
      <Content Include="Resources\Images\Logos\logosquare.scale-200.png" />
      <Content Include="Resources\Images\Logos\logosquare.scale-400.png" />
      <Content Include="Resources\Images\Logos\placeholder.scale-100.png" />
      <Content Include="Resources\Images\Logos\placeholder.scale-125.png" />
      <Content Include="Resources\Images\Logos\placeholder.scale-150.png" />
      <Content Include="Resources\Images\Logos\placeholder.scale-200.png" />
      <Content Include="Resources\Images\Logos\placeholder.scale-400.png" />
      <Content Include="Resources\Images\SquareLogo\logomediumsquare.scale-100.png" />
      <Content Include="Resources\Images\SquareLogo\logomediumsquare.scale-125.png" />
      <Content Include="Resources\Images\SquareLogo\logomediumsquare.scale-150.png" />
      <Content Include="Resources\Images\SquareLogo\logomediumsquare.scale-200.png" />
      <Content Include="Resources\Images\SquareLogo\logomediumsquare.scale-400.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.scale-100.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.scale-125.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.scale-150.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.scale-200.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.scale-400.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-16.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-16_altform-lightunplated.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-16_altform-unplated.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-24.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-24_altform-lightunplated.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-24_altform-unplated.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-256.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-256_altform-lightunplated.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-256_altform-unplated.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-32.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-32_altform-lightunplated.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-32_altform-unplated.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-48.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-48_altform-lightunplated.png" />
      <Content Include="Resources\Images\SquareLogo\logosquare.targetsize-48_altform-unplated.png" />
      <Content Include="Resources\Images\SquareLogo\placeholder.scale-100.png" />
      <Content Include="Resources\Images\SquareLogo\placeholder.scale-125.png" />
      <Content Include="Resources\Images\SquareLogo\placeholder.scale-150.png" />
      <Content Include="Resources\Images\SquareLogo\placeholder.scale-200.png" />
      <Content Include="Resources\Images\SquareLogo\placeholder.scale-400.png" />
    </ItemGroup>

   
    <ItemGroup>
        <ProjectReference Include="..\NetworkMonitorChatRazorLib\NetworkMonitorChatRazorLib.csproj" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\NetworkMonitorMaui\NetworkMonitorMaui.csproj" />
    </ItemGroup>

</Project>
