#!/bin/bash

# Check if the keypass file exists
if [ ! -f ~/code/securefiles/keypass ]; then
    echo "Error: keypass file not found at ~/code/securefiles/keypass"
    exit 1
fi

# Source the keypass file to set environment variables
. ~/code/securefiles/keypass

# Proceed with the rest of the commands
dotnet clean NetworkMonitorQuantumSecure-Android.csproj
dotnet publish ~/code/NetworkMonitor/NetworkMonitor-Maui-Android.csproj -c Release -r android --self-contained true
cp ~/code/NetworkMonitor/bin/Release/net9.0-android/android/NetworkMonitor-Maui-Android.dll ~/code/NetworkMonitorQuantumSecure/Resources/Raw/dlls/NetworkMonitor.dll
cp ./Resources/Raw/appsettings-live.json ./Resources/Raw/appsettings.json
dotnet build -c Release -f net9.0-android NetworkMonitorQuantumSecure-Android.csproj

